# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AffinityPropagationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_apWindow(object):
    def setupUi(self, apWindow):
        apWindow.setObjectName("apWindow")
        apWindow.resize(277, 178)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(apWindow.sizePolicy().hasHeightForWidth())
        apWindow.setSizePolicy(sizePolicy)
        apWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        apWindow.setDocumentMode(True)
        apWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(apWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 257, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.damping_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.damping_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.damping_label.setObjectName("damping_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.damping_label)
        self.damping_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.damping_lineEdit.setObjectName("damping_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.damping_lineEdit)
        self.convergence_iter_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.convergence_iter_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.convergence_iter_label.setObjectName("convergence_iter_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.convergence_iter_label)
        self.convergence_iter_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.convergence_iter_lineEdit.setObjectName("convergence_iter_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.convergence_iter_lineEdit)
        self.nax_iter_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.nax_iter_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nax_iter_label.setObjectName("nax_iter_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nax_iter_label)
        self.max_iter_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.max_iter_lineEdit.setObjectName("max_iter_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.max_iter_lineEdit)
        self.affinity_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.affinity_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.affinity_label.setObjectName("affinity_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.affinity_label)
        self.affinity_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.affinity_comboBox.setObjectName("affinity_comboBox")
        self.affinity_comboBox.addItem("")
        self.affinity_comboBox.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.affinity_comboBox)
        self.OKButton = QtWidgets.QPushButton(self.centralwidget)
        self.OKButton.setGeometry(QtCore.QRect(192, 140, 71, 28))
        self.OKButton.setObjectName("OKButton")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(110, 140, 71, 28))
        self.resetButton.setObjectName("resetButton")
        apWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(apWindow)
        QtCore.QMetaObject.connectSlotsByName(apWindow)

    def retranslateUi(self, apWindow):
        _translate = QtCore.QCoreApplication.translate
        apWindow.setWindowTitle(_translate("apWindow", "Affinity Propagation Parameters"))
        self.damping_label.setText(_translate("apWindow", "<html><head/><body><p align=\"right\">Damping</p></body></html>"))
        self.damping_lineEdit.setText(_translate("apWindow", "0.5"))
        self.convergence_iter_label.setText(_translate("apWindow", "Convergence Iteration"))
        self.convergence_iter_lineEdit.setText(_translate("apWindow", "15"))
        self.nax_iter_label.setText(_translate("apWindow", "Max number of iters:"))
        self.max_iter_lineEdit.setText(_translate("apWindow", "200"))
        self.affinity_label.setText(_translate("apWindow", "Affinity"))
        self.affinity_comboBox.setItemText(0, _translate("apWindow", "euclidean"))
        self.affinity_comboBox.setItemText(1, _translate("apWindow", "precomputed"))
        self.OKButton.setText(_translate("apWindow", "OK"))
        self.resetButton.setText(_translate("apWindow", "Reset"))
