# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DBSCANWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_dbScanWindow(object):
    def setupUi(self, dbScanWindow):
        dbScanWindow.setObjectName("dbScanWindow")
        dbScanWindow.resize(282, 175)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dbScanWindow.sizePolicy().hasHeightForWidth())
        dbScanWindow.setSizePolicy(sizePolicy)
        dbScanWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        dbScanWindow.setDocumentMode(True)
        dbScanWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(dbScanWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 257, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.eps_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.eps_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.eps_label.setObjectName("eps_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.eps_label)
        self.eps_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.eps_lineEdit.setObjectName("eps_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.eps_lineEdit)
        self.min_samples_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.min_samples_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.min_samples_label.setObjectName("min_samples_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.min_samples_label)
        self.min_samples_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.min_samples_lineEdit.setObjectName("min_samples_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.min_samples_lineEdit)
        self.n_jobs_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.n_jobs_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.n_jobs_label.setObjectName("n_jobs_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.n_jobs_label)
        self.n_jobs_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.n_jobs_lineEdit.setObjectName("n_jobs_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.n_jobs_lineEdit)
        self.algorithm_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.algorithm_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.algorithm_label.setObjectName("algorithm_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.algorithm_label)
        self.algorithm_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.algorithm_comboBox.setObjectName("algorithm_comboBox")
        self.algorithm_comboBox.addItem("")
        self.algorithm_comboBox.addItem("")
        self.algorithm_comboBox.addItem("")
        self.algorithm_comboBox.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.algorithm_comboBox)
        self.OKButton = QtWidgets.QPushButton(self.centralwidget)
        self.OKButton.setGeometry(QtCore.QRect(190, 140, 71, 28))
        self.OKButton.setObjectName("OKButton")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(108, 140, 71, 28))
        self.resetButton.setObjectName("resetButton")
        dbScanWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(dbScanWindow)
        QtCore.QMetaObject.connectSlotsByName(dbScanWindow)

    def retranslateUi(self, dbScanWindow):
        _translate = QtCore.QCoreApplication.translate
        dbScanWindow.setWindowTitle(_translate("dbScanWindow", "DBSCAN Parameters"))
        self.eps_label.setText(_translate("dbScanWindow", "<html><head/><body><p align=\"right\">Eps</p></body></html>"))
        self.eps_lineEdit.setText(_translate("dbScanWindow", "0.5"))
        self.min_samples_label.setText(_translate("dbScanWindow", "Number of samples"))
        self.min_samples_lineEdit.setText(_translate("dbScanWindow", "5"))
        self.n_jobs_label.setText(_translate("dbScanWindow", "Number of jobs"))
        self.n_jobs_lineEdit.setText(_translate("dbScanWindow", "1"))
        self.algorithm_label.setText(_translate("dbScanWindow", "<html><head/><body><p align=\"right\">Algorithm</p></body></html>"))
        self.algorithm_comboBox.setItemText(0, _translate("dbScanWindow", "auto"))
        self.algorithm_comboBox.setItemText(1, _translate("dbScanWindow", "ball_tree"))
        self.algorithm_comboBox.setItemText(2, _translate("dbScanWindow", "kd_tree"))
        self.algorithm_comboBox.setItemText(3, _translate("dbScanWindow", "brute"))
        self.OKButton.setText(_translate("dbScanWindow", "OK"))
        self.resetButton.setText(_translate("dbScanWindow", "Reset"))
