# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MeanShiftWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_msWindow(object):
    def setupUi(self, apWindow):
        apWindow.setObjectName("apWindow")
        apWindow.resize(277, 146)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(apWindow.sizePolicy().hasHeightForWidth())
        apWindow.setSizePolicy(sizePolicy)
        apWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        apWindow.setDocumentMode(True)
        apWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(apWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 257, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.bandwidth_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.bandwidth_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bandwidth_label.setObjectName("bandwidth_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.bandwidth_label)
        self.bandwidth_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bandwidth_lineEdit.setText("")
        self.bandwidth_lineEdit.setObjectName("bandwidth_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bandwidth_lineEdit)
        self.n_jobs_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.n_jobs_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.n_jobs_label.setObjectName("n_jobs_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.n_jobs_label)
        self.n_jobs_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.n_jobs_lineEdit.setObjectName("n_jobs_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.n_jobs_lineEdit)
        self.nax_iter_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.nax_iter_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nax_iter_label.setObjectName("nax_iter_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nax_iter_label)
        self.max_iter_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.max_iter_lineEdit.setObjectName("max_iter_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.max_iter_lineEdit)
        self.OKButton = QtWidgets.QPushButton(self.centralwidget)
        self.OKButton.setGeometry(QtCore.QRect(190, 110, 71, 28))
        self.OKButton.setObjectName("OKButton")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(108, 110, 71, 28))
        self.resetButton.setObjectName("resetButton")
        apWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(apWindow)
        QtCore.QMetaObject.connectSlotsByName(apWindow)

    def retranslateUi(self, apWindow):
        _translate = QtCore.QCoreApplication.translate
        apWindow.setWindowTitle(_translate("apWindow", "Mean-Shift Parameters"))
        self.bandwidth_label.setText(_translate("apWindow", "<html><head/><body><p align=\"right\">Bandwidth</p></body></html>"))
        self.n_jobs_label.setText(_translate("apWindow", "Number of jobs"))
        self.n_jobs_lineEdit.setText(_translate("apWindow", "1"))
        self.nax_iter_label.setText(_translate("apWindow", "Max number of iters:"))
        self.max_iter_lineEdit.setText(_translate("apWindow", "300"))
        self.OKButton.setText(_translate("apWindow", "OK"))
        self.resetButton.setText(_translate("apWindow", "Reset"))
